### ISSUE TITLE
Error while running Ciffar-10

### ISSUE THREAD

**Issue by Addhi86** [bazilas/matconvnet-ResNet#2]
Hello, Thank you very much for the code. 
I am running it on the Matlab 2015b. 
I am getting this error
![image](https://user-images.githubusercontent.com/22164098/31164722-15af298c-a934-11e7-80df-e067c16ba228.png)
Do you have any idea what's the issue?

**Comment by Addhi86** [comment]
Its working now.. I forgot to run vl_compilenn.

Is it possible to use the  net after training as pretrained network?

**Comment by bazilas** [comment]
sure
