### ISSUE TITLE
Failures happened on ResNet initialization with MATLAB R2014a or R2014b.

### ISSUE THREAD

**Issue by gaobb** [bazilas/matconvnet-ResNet#2]
Error in dagnn.DagNN/rebuild>dagSort (line 87)
      order = dagSort(obj, hops, order, child) ;

Error in dagnn.DagNN/rebuild>dagSort (line 87)
      order = dagSort(obj, hops, order, child) ;

**Comment by bazilas** [comment]
You might want to try with small depths (e.g 20 or 38) to see if the problem occurs because of the network's depth.

Which version of matlab do you use? I tested with 2015b and 2016a (there were some problems with versions of 2014).

**Comment by gaobb** [comment]
Thanks for your reply. I run this code with MATLAB 2014a. The reason of failures may be the version of matlab. I will try to do with 2015b or 2016a. Thank you again!

**Comment by gaobb** [comment]
The reason of ResNet initialization failures on matlab R2014a or R2014b is 'Maximum recursion limit 500 reached' .

So the issue can be fixed as follow:
N = 600; % >=500
set(0,'RecursionLimit',N);

Now, it can work. cool.....
train: epoch 01:   1/391: 4.5 (4.5) Hz error: 0.89844 objective: 2.34692
train: epoch 01:   2/391: 4.6 (4.6) Hz error: 0.89844 objective: 2.33492
train: epoch 01:   3/391: 4.7 (4.7) Hz error: 0.89844 objective: 2.33826
train: epoch 01:   4/391: 4.7 (4.8) Hz error: 0.90430 objective: 2.34222
train: epoch 01:   5/391: 4.7 (4.7) Hz error: 0.91094 objective: 2.34341
train: epoch 01:   6/391: 4.7 (4.6) Hz error: 0.90885 objective: 2.34255
train: epoch 01:   7/391: 4.7 (4.6) Hz error: 0.91071 objective: 2.33856
train: epoch 01:   8/391: 4.7 (4.6) Hz error: 0.91016 objective: 2.33518
train: epoch 01:   9/391: 4.7 (4.7) Hz error: 0.90017 objective: 2.32876
