### ISSUE TITLE
Mean subtraction

### ISSUE THREAD

**Issue by assafmushinsky** [bazilas/matconvnet-ResNet#4]
You wrote:

r = data(:,:,1,set == 1);
g = data(:,:,3,set == 1);
b = data(:,:,3,set == 1);

Did you mean:

r = data(:,:,1,set == 1);
g = data(:,:,2,set == 1);
b = data(:,:,3,set == 1);

or is it on purpose?

**Comment by bazilas** [comment]
thanks for the correction! I will push it
